spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/xiangxue?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapping/*.xml

